name = "«Lean_LIPO»"
defaultTargets = ["«UpperBound»"]

[leanOptions]
pp.unicode.fun = true
pp.proofs.withType = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_exe]]
name = "«UpperBound»"